### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by banhegyinorbert** [smblott-github/intent_radio#3]
Hello,

I appreciate your work. I've read your summary about other apps and I have a problem with XiiaLive. I can not get the actually played song metadata (title, artist...). (Since on the dev's page noone gives no respond I thought I'd rather ask a pro.) Could you help me how make a Tasker profile that receives the data?

thanks,

Norbert

**Comment by smblott-github** [comment]
I don't know any more than what's on the Xiialive web site... http://support.xiialive.com/topic/288891-xiialive-open-apis-for-android/
