### ISSUE TITLE
MP3 streams not working

### ISSUE THREAD

**Issue by fbreitwieser** [smblott-github/intent_radio#4]
Thank you for this great project. While the BBC streams work just find for me, those that I tried to add don't. Specifically:

Radio Oe1: http://mp3stream3.apasf.apa.at:8000/listen.pls
Radio Wien: http://mp3stream2.apasf.apa.at:8000/listen.pls
FM4: http://mp3stream1.apasf.apa.at:8000/listen.pls
WEAA: http://amber.streamguys.com:4020/live
WYPR: http://live.str3am.com:2410/wypr.m3u

**Comment by smblott-github** [comment]
Thanks for the feedback, @fbreitwieser.

All five of those streams are working for me.  Perhaps you might double check that you have the broadcast intents set up correctly?

**Comment by fbreitwieser** [comment]
Thanks for the quick answer. Sorry I did not reply enough information in the issue. I used Intent Radio through shorty (https://github.com/billthefarmer/shorty) and not with tasker. Now I set up the project with Tasker, and indeed it works. Thank you!
