### ISSUE TITLE
aac streams not playing or taking too long to buffer

### ISSUE THREAD

**Issue by ertmuirm** [smblott-github/intent_radio#5]
the following streams either take very long to buffer (>30s), in which case they are of poor quality, or do not play at all:
http://sc.rastream.com:8950/listen.pls?sid=1
http://sc.rastream.com:8905/listen.pls?sid=1

the following streams are duplicates of the above but don't play at all in intent radio (but play perfectly in the browser or MX player):
http://mediacorp.rastream.com/950fm
http://mediacorp.rastream.com/905fm

**Comment by smblott-github** [comment]
For these:

    http://sc.rastream.com:8950/listen.pls?sid=1
    http://sc.rastream.com:8905/listen.pls?sid=1

... perhaps try them like this...

    http://sc.rastream.com:8950/listen.pls
    http://sc.rastream.com:8905/listen.pls

(IR is pretty dumb about detecting playlists.)

Not sure what's up with the other two.  IR just passes them to the [Android Media Player](http://developer.android.com/reference/android/media/MediaPlayer.html).

**Comment by ertmuirm** [comment]
thanks for the quick reply! i tried both of these like you suggested, and
they play but with a 30s lag and the audio is spotty. what's strange is
that on a browser or MXplayer, it starts playing almost instantaneously
(<2s) and quality is good.

http://sc.rastream.com:8950/listen.pls
http://sc.rastream.com:8905/listen.pls

can anything be done on my end to solve the lag and quality issues?
